### ISSUE TITLE
Use Git History for PDF Changes

### ISSUE THREAD

**Issue by infogulch** [vdavez/scotus-servo#3]
It may be advantageous to keep a single pdf file for a current opinion and updating the binary pdf when a new revision is posted instead of adding the file with a unique name and updating the etags to match.

Github has a history of adding visual diffs for different file types (like [psd](https://github.com/blog/1845-psd-viewing-diffing), [rendered prose](https://github.com/blog/1784-rendered-prose-diffs), [maps](https://github.com/blog/1772-diffable-more-customizable-maps), [images](https://github.com/blog/817-behold-image-view-modes), and [3D files](https://github.com/blog/1633-3d-file-diffs)), it's likely that support for PDF diffs will be added eventually (there are [several](https://github.com/vslavik/diff-pdf) [libraries](http://www.qtrac.eu/diffpdf.html) for pdf diffing already). If this happens, using the built-in diff tool would become extremely useful, but only if the file itself is changed.

Edit: On second thought, this may be a case of me misunderstanding the file organization of the repository.

**Comment by vdavez** [comment]
Thanks for the comment. For this exact reason, I changed the file naming convention here: https://github.com/vzvenyach/scotus-servo/commit/26a768b6ad0298ee89e956a270412da1ea5e19b0. Thus, even though one of today's opinions is named `13-299_6k4c.pdf` by SCOTUS, the saved version is at `13-299.pdf`. I didn't go _backwards_ because earlier opinions used different naming conventions (e.g. 08-1394Reissue.pdf). But going forward, it should work.

**Comment by vdavez** [comment]
I took the plunge and fixed this for 2013's opinions. Thanks again!

**Comment by infogulch** [comment]
Thanks! :thumbsup:
